services:
  database:
    container_name: 'computadores-db'
    image: 'postgres:16.4-alpine'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'computadores'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: 'computadores-backend'
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_TYPE: 'postgres'
      PG_HOST: 'database'
      PG_USER: 'postgres'
      PG_PASSWORD: 'postgres'
      PG_DB: 'computadores'
    depends_on:
      - database

  frontend:
    container_name: 'computadores-frontend'
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5173:5173'
    environment:
      VITE_API_BASE_URL: 'http://localhost:3000'
    depends_on:
      - backend

volumes:
  postgres_data:
